#!/usr/bin/env python3
"""Generate docs/VENDOR-INDEX.md -- every function in vendor/, with its line span.

WHY THIS EXISTS, IN MONEY.

`vendor/Bandits/mods/Bandits/42.20/media/lua/client/BanditUpdate.lua` is 2,492 lines. Reading
it whole costs roughly 30,000 tokens. Three code reviews in a row opened it in slices to
recover the same handful of facts -- the task dispatcher's state machine, the ManageCollisions
guards, where ManageCombat clears the queue -- and every one of those reviews named it in its
own cost report as the largest read it made.

The whole vendored tree is 678,787 lines. Nobody should ever be paying to search it by reading.

What an agent actually needs is almost never the file: it is "where is X defined, and how long
is it", so it can read thirty lines instead of two thousand. That is a lookup table, it is
derivable, and this generates it.

THE DECLARATION-STYLE TRAP, which is why this is a script and not a grep. Bandits declares
functions three different ways in the same codebase:

    function Bandit.ClearTasks(zombie)          -- the obvious one
    local function ManageCombat(bandit)         -- file-local, invisible to a caller
    ZombieActions.Move.onStart = function(...)  -- assignment; `grep "function Move.onStart"`
                                                   finds NOTHING

That third form has hidden entire libraries from people grepping for them, and it is how the
`ZombieActions` handlers are written -- the exact files this project reads most.

Regenerate after `./tools/deps.py update`. The output is derived: never hand-edit it.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "VENDOR-INDEX.md"

# All three declaration styles. The third is the one that matters -- see the module docstring.
PATTERNS = [
    re.compile(r"^\s*function\s+([\w.:]+)\s*\("),
    re.compile(r"^\s*local\s+function\s+([\w.]+)\s*\("),
    re.compile(r"^\s*([\w.]+)\s*=\s*function\s*\("),
]

# Files big enough that reading one whole is a real cost. Everything is indexed, but these get
# called out at the top so the expensive ones are the first thing anybody sees.
BIG = 400


def functions_in(path):
    """Every function in one file as (name, start, end). `end` is the line before the next
    declaration, which is an approximation -- good enough to read a span, never quoted as a
    boundary."""
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    found = []
    for n, line in enumerate(lines, 1):
        code = line.split("--", 1)[0]
        for rx in PATTERNS:
            m = rx.match(code)
            if m:
                found.append([m.group(1), n, None])
                break

    for i, entry in enumerate(found):
        entry[2] = (found[i + 1][1] - 1) if i + 1 < len(found) else len(lines)
    return found, len(lines)


# ONLY THE VERSION THE GAME LOADS, AND ONLY THE LIVE COPY.
#
# The first run of this script indexed everything under vendor/ and produced a 948 KB file --
# an index more expensive to read than the problem it was written to solve, which is the
# funniest possible way to fail at this. The cause is that vendor/ ships 42.12 through 42.20
# side by side, plus a whole `Bandits.old` tree, so `BanditUpdate.lua` was indexed FOURTEEN
# times and the one copy anybody needs was buried among thirteen that are never loaded.
#
# The game loads exactly one version folder, the one matching its build. Everything else is
# there for diffing upgrades and must never appear in a citation -- `audit.py`'s `vendor` check
# BLOCKS on a citation missing its version folder for precisely this reason (GetAccessSquare
# moved 17 lines between 42.18 and 42.20).
#
# Keep this list in step with the build in CLAUDE.md after `./tools/deps.py update`.
LIVE = ("/42.20/", "/common/")
SKIP = (".old",)


def is_live(path):
    rel = str(path)
    if any(s in rel for s in SKIP):
        return False
    return any(v in rel for v in LIVE)


def main():
    files = sorted(p for p in ROOT.glob("vendor/**/media/lua/**/*.lua") if is_live(p))
    if not files:
        print("no live vendored Lua found -- check LIVE against the folders in vendor/",
              file=sys.stderr)
        return 1

    index, big = {}, []
    total_fns = 0
    for path in files:
        fns, nlines = functions_in(path)
        if not fns:
            continue
        rel = str(path.relative_to(ROOT))
        index[rel] = fns
        total_fns += len(fns)
        if nlines >= BIG:
            big.append((nlines, rel, len(fns)))
    big.sort(reverse=True)

    out = []
    out.append("# Vendor index — where everything is, without reading anything\n")
    out.append("**Generated by `./tools/vendorindex.py`. Never hand-edit; regenerate after "
               "`./tools/deps.py update`.**\n")
    out.append(f"{total_fns:,} functions across {len(index):,} vendored Lua files "
               f"({sum(n for n, _, _ in big):,} lines in the large ones alone).\n")
    out.append("**GREP THIS FILE, DO NOT READ IT.** It is a lookup table, not a document — "
               "reading it whole costs more than the problem it solves. One line answers the "
               "question:\n")
    out.append("```bash\ngrep -n 'ManageCombat' docs/VENDOR-INDEX.md\n"
               "#   | `ManageCombat` | 898-1230 |\n```\n")
    out.append("Then read ONLY that span. Opening a 2,000-line vendored file to recover three "
               "facts is how three reviews in a row spent their largest read.\n")
    out.append("For what the framework MEANS rather than where it lives, read "
               "[`BANDITS-API.md`](BANDITS-API.md) first — it carries the task dispatcher, the "
               "queue and lock rules, and the traps that have each cost a play session.\n")

    out.append("\n## The expensive files\n")
    out.append("Reading any of these whole is a mistake. Line counts are the reason.\n")
    out.append("| Lines | File | Functions |")
    out.append("|---:|---|---:|")
    for nlines, rel, nfns in big[:15]:
        out.append(f"| {nlines:,} | `{rel}` | {nfns} |")

    out.append("\n## Every function, by file\n")
    for rel in sorted(index):
        out.append(f"\n### `{rel}`\n")
        out.append("| Function | Lines |")
        out.append("|---|---|")
        for name, start, end in index[rel]:
            span = f"{start}" if end - start < 2 else f"{start}-{end}"
            out.append(f"| `{name}` | {span} |")

    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  --  {total_fns:,} functions, {len(index):,} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
